# Generated by Django 6.0.7 on 2026-07-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='review_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
